spring:
  application:
    name: segurancaAPI
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_Sql: true
jwt:
  secret: ${JWT_SECRET:change-me-in-env}
  expiration: 3600
  issuer: segurancaAPI

